### ISSUE TITLE
Cannot install standalone app in Ubuntu 16.04

### ISSUE THREAD

**Issue by malivp3494** [facebook/react-devtools#1038]
So, I tried to install react-devtools standalone app by
``` npm install -g react-devtools```
apparently, it doesn't seem to work for me.
I get the following output 
```
> electron@1.8.7 postinstall /home/toxicdesire/.npm-global/lib/node_modules/react-devtools/node_modules/electron
> node install.js

Downloading electron-v1.8.7-linux-x64.zip
[============================================>] 100.0% of 47.22 MB (65.05 kB/s)
/home/toxicdesire/.npm-global/lib/node_modules/react-devtools/node_modules/electron/install.js:47
  throw err
  ^

Error: Generated checksum for "electron-v1.8.7-linux-x64.zip" did not match expected checksum.
    at ChecksumMismatchError.ErrorWithFilename (/home/toxicdesire/.npm-global/lib/node_modules/react-devtools/node_modules/sumchecker/build.js:41:124)
    at new ChecksumMismatchError (/home/toxicdesire/.npm-global/lib/node_modules/react-devtools/node_modules/sumchecker/build.js:56:133)
    at Hash.<anonymous> (/home/toxicdesire/.npm-global/lib/node_modules/react-devtools/node_modules/sumchecker/build.js:203:22)
    at emitNone (events.js:106:13)
    at Hash.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Hash.Readable.push (_stream_readable.js:208:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.7 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by malivp3494** [comment]
So after some digging, it turns out to be an issue with ```sumchecker``` used in electron. 
<br>To fix this, you would have to use the following command:<br>
```npm install -g electron --unsafe-perm=true --allow-root```
<br> Also, if you haven't changed your global npm directory, you should do that, as it's messy to use npm with sudo. refer [this](https://docs.npmjs.com/getting-started/fixing-npm-permissions) to change the global npm modules directory so that you don't have to use ```sudo``` anymore
