### ISSUE TITLE
[New Devtools] Warnings with Immutable.js

### ISSUE THREAD

**Issue by prakhar1989** [facebook/react-devtools#106]
Hi,

I just tried the new React DevTools and I found that it generated a bunch of *warnings* as pasted below. Since I use Immutable collections as props, I'd wager that this is where the warnings are coming from. 

```
bundle.js:2 iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at le.Object.defineProperty.get (http://prakhar.me/react-surveyman/build/bundle.js:2:473)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:50:21)
    at eval (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:57:14)
    at Array.map (native)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:56:17)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at eval (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:178:19)
    at Array.map (native)
    at Bridge.flush (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:173:33)
```

Let me know if you need any more detail for this. You can see the application live [here](http://prakhar.me/react-surveyman/)

Thanks,

**Comment by AdamBoxall** [comment]
+1

**Comment by JamesHageman** [comment]
+1

**Comment by dzannotti** [comment]
+1
