### ISSUE TITLE
When using immutable if react devtools beta is enabled, an ominous warning appears.

### ISSUE THREAD

**Issue by danmartinez101** [facebook/react-devtools#171]
```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Record.Object.defineProperty.get (webpack:///./~/immutable/dist/immutable.js?:4602:21)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:50:21)
    at eval (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:57:14)
    at Array.map (native)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:56:17)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at dehydrate (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:198:2), <anonymous>:70:17)
    at eval (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:178:19)
    at Array.map (native)
    at Bridge.flush (eval at <anonymous> (chrome-extension://lkefdminonoajpbbbemjloccljgfaokc/build/backend.js:72:2), <anonymous>:173:33)
```

If I disabled the devtools, this no longer shows up in the console.

Possibly related to #52

**Comment by ngyikp** [comment]
Duplicate of #132, #126, #125 and #106

**Comment by danmartinez101** [comment]
Guess I need to remember to search closed issues
