### ISSUE TITLE
[React Native] Sometimes DevTools will interrupt debugger websocket

### ISSUE THREAD

**Issue by jhen0409** [facebook/react-devtools#399]
It seems [this line](https://github.com/facebook/react-devtools/blob/master/shells/electron/src/ui.js#L85) will sends too many messages, mostly `hideHighlight` event. (I try to quickly move the cursor between nodes)

Although I don't think this will affect the debugger connection, but it really happened if DevTools send too many messages:

![2016-07-12 6 34 33](https://cloud.githubusercontent.com/assets/3001525/16749250/703a705a-47fb-11e6-8a03-af0fb0bcef9f.png)

It's can be reproduce on RN Inspector for Nuclide and Electron build. I tested a lot of times. 😂

Also, sometimes I can get the error on React Native local server:

```
ERROR  out of range index
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/path/to/project/node_modules/ws/lib/Receiver.js:386:24)
    at Receiver.add (/path/to/project/node_modules/ws/lib/Receiver.js:86:3)
    at Socket.realHandler (/path/to/project/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

**Comment by jhen0409** [comment]
Sorry my bad, maybe just related to https://github.com/facebook/react-native/issues/8668, when I was back node 6.2 it doesn't happen.
