### ISSUE TITLE
React DevTools throwing 'Attempting to use a disconnected port object' in Chrome

### ISSUE THREAD

**Issue by hyendler** [facebook/react-devtools#461]
Tried debugging per instructions on README, but all I see is this error.

**Comment by charlesjavelona** [comment]
Got the same thing, here is where it's happening.

```javascript
// Sends a message asynchronously to the context on the other end of this
  // port.
  PortImpl.prototype.postMessage = function(msg) {
    if (!$Object.hasOwnProperty(ports, this.portId_))
      throw new Error(kPortClosedError);
```

Here is a snippet:

```javascript
Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:64:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:149:26)
    at responseCallback (extensions::messaging:177:16)
    at chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:1:8030
    at i (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:16:8658)
    at chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:14:7972
    at i (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:16:8658)
    at i._settlePromiseFromHandler (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:15:13765)
    at i._settlePromise (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:15:14568)
    at i._settlePromise0 (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:15:15269)
    at i._settlePromises (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:15:16488)
    at o._drainQueue (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:14:3159)
    at o._drainQueues (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:14:3220)
    at drainQueues (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:14:1261)
```

**Comment by gaearon** [comment]
The stack trace above doesn't seem to come from React DevTools. 
If you look at extension ID, it corresponds to some Chrome extension called ["Honey"](https://chrome.google.com/webstore/detail/honey/bmnlcjabgnpnenekpadlanbbkooimhnj).

I would suggest disabling all other extensions and trying again. If you still have the problem please let me know!
