### ISSUE TITLE
yarn add --dev react-devtools warns about electron vulnerability

### ISSUE THREAD

**Issue by rmdevos** [facebook/react-devtools#898]
```
07:28 $ yarn add --dev react-devtools
yarn add v1.0.0
[1/4] 🔍  Resolving packages...
warning electron@1.8.0: this beta version of electron has been removed due to a security vulnerability. To get the latest beta, run 'npm install electron@beta'
warning object-keys@0.4.0:
[2/4] 🚚  Fetching packages...
warning Pattern ["object-assign@latest"] is trying to unpack in the same destination "/Users/ramsy/Library/Caches/Yarn/v1/npm-object-assign-4.1.1-2109adc7965887cfc05cbbd442cac8bfbb360863" as pattern ["object-assign@^4.1.0","object-assign@^4","object-assign@^4.1.1","object-assign@^4.0.1"]. This could result in a non deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning "ajv-keywords@2.1.0" has incorrect peer dependency "ajv@>=5.0.0".
[4/4] 📃  Building fresh packages...
[-/3] ⠐ waiting...
[-/3] ⠐ waiting...
[3/3] ⠐ electron
[-/3] ⠐ waiting...
error /Users/ramsy/Workspace/reactjs/indecision/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/ramsy/Workspace/reactjs/indecision/node_modules/electron
Output:
/Users/ramsy/Workspace/reactjs/indecision/node_modules/electron/install.js:48
  throw err
  ^

Error: Failed to find Electron v1.8.0 for darwin-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-darwin-x64.zip
    at Request.<anonymous> (/Users/ramsy/Workspace/reactjs/indecision/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestResponse (/Users/ramsy/Workspace/reactjs/indecision/node_modules/nugget/node_modules/request/request.js:1068:10)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
```

**Comment by bvaughn** [comment]
React DevTools has been rewritten and [recently launched a new version 4 UI](https://reactjs.org/blog/2019/08/15/new-react-devtools.html). The source code for this rewrite was done in a separate repository and now lives in the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)).

Because version 4 was a total rewrite, and all issues in this repository are related to the old version 3 of the extension, I am closing all issues in this repository. If you can still reproduce this issue, or believe this feature request is still relevant, please open a new issue in the React repo: https://github.com/facebook/react/issues/new?labels=Component:%20Developer%20Tools
