### ISSUE TITLE
react-devtools npm install error

### ISSUE THREAD

**Issue by mymmoonoa** [facebook/react-devtools#934]
I followed the [react-native official guide](http://facebook.github.io/react-native/docs/debugging.html#content)to install react-devtools.

```
$ npm install -g react-devtools
/usr/local/bin/react-devtools -> /usr/local/lib/node_modules/react-devtools/bin.js

> electron@1.7.9 postinstall /usr/local/lib/node_modules/react-devtools/node_modules/electron
> node install.js

/usr/local/lib/node_modules/react-devtools/node_modules/electron/install.js:48
  throw err
  ^

Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:606:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hairongwang/.npm/_logs/2017-11-01T02_07_59_983Z-debug.log
```
---
If I add sudo, error different:
```
sudo npm install -g react-devtools
Password:
/usr/local/bin/react-devtools -> /usr/local/lib/node_modules/react-devtools/bin.js

> electron@1.7.9 postinstall /usr/local/lib/node_modules/react-devtools/node_modules/electron
> node install.js

/usr/local/lib/node_modules/react-devtools/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/react-devtools/node_modules/electron/electron-tmp-download-28598-1509502833525'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hairongwang/.npm/_logs/2017-11-01T02_20_35_503Z-debug.log
```
Any help? thanks in advance!

**Comment by mymmoonoa** [comment]
error log: [2017-11-01T02_07_59_983Z-debug.log](https://github.com/facebook/react-devtools/files/1432905/2017-11-01T02_07_59_983Z-debug.log)

**Comment by mymmoonoa** [comment]
After command ```sudo npm uninstall electron -g```
error changes 
```
npm install -g react-devtools
/usr/local/bin/react-devtools -> /usr/local/lib/node_modules/react-devtools/bin.js

> electron@1.7.9 postinstall /usr/local/lib/node_modules/react-devtools/node_modules/electron
> node install.js

/usr/local/lib/node_modules/react-devtools/node_modules/electron/install.js:48
  throw err
  ^

Error: connect ETIMEDOUT 52.216.224.216:443
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hairongwang/.npm/_logs/2017-11-01T02_42_44_022Z-debug.log
```
Again I tried ```npm install -g react-devtools```
looks like process get stuck forever:
```
$ npm install -g react-devtools
/usr/local/bin/react-devtools -> /usr/local/lib/node_modules/react-devtools/bin.js

> electron@1.7.9 postinstall /usr/local/lib/node_modules/react-devtools/node_modules/electron
> node install.js   
<<<<<<<<< nothing changes here
```

**Comment by mymmoonoa** [comment]
After update npm to version 5.5.1, I use proxy at home, Setup is ok now.
```
> electron@1.7.9 postinstall /usr/local/lib/node_modules/react-devtools/node_modules/electron
> node install.js

+ react-devtools@2.5.2
added 232 packages in 433.924s
```
seems network is the key point.

**Comment by prashen** [comment]
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/react-devtools/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/appsdeveloper/.npm/_logs/2019-02-01T10_29_58_849Z-debug.log

my npm version is 5.5.1 but still can't install it.

**Comment by prashen** [comment]
I have tried this and it's installed sudo npm install -g react-devtools --unsafe-perm=true

I followed sudo npm install electron --unsafe-perm=true
Electron has a installation problem so I tried this.

source: https://electronjs.org/docs/tutorial/installation
